# Generated by Django 5.2.7 on 2025-11-13 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order', 'Pedido'), ('chat', 'Chat'), ('product', 'Producto'), ('system', 'Sistema'), ('payment', 'Pago'), ('info', 'Información')], default='info', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.CharField(blank=True, help_text='URL a la que redirige la notificación', max_length=500, null=True, verbose_name='Enlace')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del objeto relacionado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_notific_user_id_0abebb_idx'), models.Index(fields=['user', 'is_read'], name='app_notific_user_id_e95a5f_idx')],
            },
        ),
    ]
