# Generated by Django 5.2.7 on 2025-11-15 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_room_chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='attended_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se atendió la cotización', null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='attended_by',
            field=models.ForeignKey(blank=True, help_text='Administrador que atendió la cotización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
