# Generated by Django 5.2.6 on 2025-11-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CUSTOMER', 'Cliente')], default='CUSTOMER', max_length=10, verbose_name='Rol del usuario'),
        ),
    ]
