# Generated by Django 5.2.7 on 2025-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Correo_Electronico',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
